---
- hosts: all 
  sudo: yes 
  tasks:
    - user: name=abeltre1 comment="abeltre1 root"
    - name: Set authorized key from URL 
      authorized_key: user=abeltre1 key="{{ lookup('file','/etc/ansible/files/authorized_keys.abeltre1.pub')}}"
    
    - name: Install vim 
      apt: pkg=vim state=installed update_cache=true
      notify:
        - start vim
    - name: directory Maker 
      file: path=/home/abeltre1/src state=directory  mode=0777   
     
    - name: Create test file 
      file: path=/home/abeltre1/testing.txt state=touch 

    - name: Deleting a directory
      shell: rm -r /home/abeltre1/src 


    - stat: path=/home/abeltre1/testing.txt
      register: file_path

    - debug: msg="File exists"
      when: file_path.stat.exists == true  

  handlers:
    - name: Start vim
      service: name=vim state=started
